export const HOME_FEATURED_IS_LOADING = 'HOME_FEATURED_IS_LOADING';
export const HOME_FEATURED_LOAD_FAILED = 'HOME_FEATURED_LOAD_FAILED';
export const HOME_FEATURED_LOAD_SUCCESS = 'HOME_FEATURED_LOAD_SUCCESS';

export const HOME_TRENDING_IS_LOADING = 'HOME_TRENDING_IS_LOADING';
export const HOME_TRENDING_LOAD_FAILED = 'HOME_TRENDING_LOAD_FAILED';
export const HOME_TRENDING_LOAD_SUCCESS = 'HOME_TRENDING_LOAD_SUCCESS';

export const PRODUCTS_POPULAR_IS_LOADING = 'PRODUCTS_POPULAR_IS_LOADING';
export const PRODUCTS_POPULAR_LOAD_FAILED = 'PRODUCTS_POPULAR_LOAD_FAILED';
export const PRODUCTS_POPULAR_LOAD_SUCCESS = 'PRODUCTS_POPULAR_LOAD_SUCCESS';

export const PRODUCTS_TRENDING_IS_LOADING = 'PRODUCTS_TRENDING_IS_LOADING';
export const PRODUCTS_TRENDING_LOAD_FAILED = 'PRODUCTS_TRENDING_LOAD_FAILED';
export const PRODUCTS_TRENDING_LOAD_SUCCESS = 'PRODUCTS_TRENDING_LOAD_SUCCESS';

export const HOME_SEGMENT_1_IS_LOADING = 'HOMESEGMENT_1_IS_LOADING';
export const HOME_SEGMENT_1_LOAD_FAILED = 'HOME_SEGMENT_1_LOAD_FAILED';
export const HOME_SEGMENT_1_LOAD_SUCCESS = 'HOME_SEGMENT_1_LOAD_SUCCESS';

export const HOME_SEGMENT_2_IS_LOADING = 'HOMESEGMENT_2_IS_LOADING';
export const HOME_SEGMENT_2_LOAD_FAILED = 'HOME_SEGMENT_2_LOAD_FAILED';
export const HOME_SEGMENT_2_LOAD_SUCCESS = 'HOME_SEGMENT_2_LOAD_SUCCESS';

export const USER_IS_LOGGING_IN = 'USER_IS_LOGGING_IN';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';

export const USER_IS_VERIFYING = 'USER_IS_VERIFYING';
export const USER_VERIFY_FAILED = 'USER_VERIFY_FAILED';
export const USER_VERIFY_SUCCESS = 'USER_VERIFY_SUCCESS';
export const USER_RESEND_TAC_SUCCESS = 'USER_RESEND_TAC_SUCCESS';

export const USER_IS_REGISTERING = 'USER_IS_REGISTERING';
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';

export const DASH_SUBS_IS_LOADING = 'DASH_SUBS_IS_LOADING';
export const DASH_SUBS_LOAD_FAILED = 'DASH_SUBS_LOAD_FAILED';
export const DASH_SUBS_LOAD_SUCCESS = 'DASH_SUBS_LOAD_SUCCESS';

export const DASH_RECOM_IS_LOADING = 'DASH_RECOM_IS_LOADING';
export const DASH_RECOM_LOAD_FAILED = 'DASH_RECOM_LOAD_FAILED';
export const DASH_RECOM_LOAD_SUCCESS = 'DASH_RECOM_LOAD_SUCCESS';

export const SUBSCRIPTION_IS_LOADING = 'SUBSCRIPTION_IS_LOADING';
export const SUBSCRIPTION_LOAD_FAILED = 'SUBSCRIPTION_LOAD_FAILED';
export const SUBSCRIPTION_LOAD_SUCCESS = 'SUBSCRIPTION_LOAD_SUCCESS';

export const UNSUBSCRIBE_IS_LOADING = 'UNSUBSCRIBE_IS_LOADING';
export const UNSUBSCRIBE_LOAD_FAILED = 'UNSUBSCRIBE_LOAD_FAILED';
export const UNSUBSCRIBE_LOAD_SUCCESS = 'UNSUBSCRIBE_LOAD_SUCCESS';
export const UNSUBSCRIBE_CLEAR_STATE = 'UNSUBSCRIBE_CLEAR_STATE';

export const PROFILE_IS_LOADING = 'PROFILE_IS_LOADING';
export const PROFILE_LOAD_FAILED = 'PROFILE_LOAD_FAILED';
export const PROFILE_LOAD_SUCCESS = 'PROFILE_LOAD_SUCCESS';

export const CATEGORY_LIST_LOAD_FAILED = 'CATEGORY_LIST_LOAD_FAILED';
export const CATEGORY_LIST_LOADED = 'CATEGORY_LIST_LOADED';

export const SEARCH_IS_LOADING = 'SEARCH_IS_LOADING';
export const SEARCH_LOAD_FAILED = 'SEARCH_LOAD_FAILED';
export const SEARCH_LOADED = 'SEARCH_LOADED';